import { Router, type IRouter } from "express";
import healthRouter from "./health";
import businessesRouter from "./businesses";
import categoriesRouter from "./categories";
import reviewsRouter from "./reviews";
import enquiriesRouter from "./enquiries";
import productsRouter from "./products";
import blogRouter from "./blog";
import analyticsRouter from "./analytics";
import settingsRouter from "./settings";
import adminUsersRouter from "./admin_users";
import popupsRouter from "./popups";
import communityPartnersRouter from "./community_partners";
import governmentContactsRouter from "./government_contacts";
import carouselRouter from "./carousel";
import customPagesRouter from "./custom_pages";
import businessReportsRouter from "./business_reports";
import searchRouter from "./search";
import webdevRouter from "./webdev";
import leadsRouter from "./leads";
import exportRouter from "./export";
import uploadRouter from "./upload";
import authRouter from "./auth";
import warningsRouter from "./warnings";
import deletionRequestsRouter from "./deletion_requests";
import notificationsRouter from "./notifications";
import supportTicketsRouter from "./support_tickets";
import announcementsRouter from "./announcements";
import reactivationRouter from "./reactivation";
import rankingRouter from "./ranking";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/businesses", businessesRouter);
router.use("/categories", categoriesRouter);
router.use("/reviews", reviewsRouter);
router.use("/enquiries", enquiriesRouter);
router.use("/products", productsRouter);
router.use("/blog", blogRouter);
router.use("/analytics", analyticsRouter);
router.use("/settings", settingsRouter);
router.use("/users", adminUsersRouter);
router.use("/popups", popupsRouter);
router.use("/community-partners", communityPartnersRouter);
router.use("/government-contacts", governmentContactsRouter);
router.use("/carousel", carouselRouter);
router.use("/pages", customPagesRouter);
router.use("/reports", businessReportsRouter);
router.use("/search", searchRouter);
router.use("/webdev", webdevRouter);
router.use("/leads", leadsRouter);
router.use("/warnings", warningsRouter);
router.use("/export", exportRouter);
router.use(uploadRouter);
router.use("/admin", authRouter);
router.use("/deletion-requests", deletionRequestsRouter);
router.use("/notifications", notificationsRouter);
router.use("/support-tickets", supportTicketsRouter);
router.use("/announcements", announcementsRouter);
router.use("/reactivation", reactivationRouter);
router.use("/ranking", rankingRouter);

export default router;
